# アプリケーション名
spring.application.name=tasklist

# H2データベースの接続先
# ./data/taskdb というファイルに保存される
spring.datasource.url=jdbc:h2:./data/taskdb

# H2ドライバ
spring.datasource.driver-class-name=org.h2.Driver

# ユーザー名
spring.datasource.username=sa

# パスワード
spring.datasource.password=

# H2コンソールを有効にする
spring.h2.console.enabled=true

# H2コンソールのURL
spring.h2.console.path=/h2-console

# Entityクラスを見てテーブルを自動更新する
spring.jpa.hibernate.ddl-auto=update

# 実行されるSQLをログに表示する
spring.jpa.show-sql=true